WIDTH = 1200
HEIGHT = 800

HIGHWAY_COST = 1
MAIN_ROAD_COST = 1.2
MINOR_ROAD_COST = 1.5
RURAL_ROAD_COST = 1.71
SLOW_ROAD_COST = 2.4
STREET_COST = 4

METROPOLIS = 1
URBAN_AREA = 1.2
TOWN = 1.5
VILLAGE = 1.71
HAMLET = 2.4


EDGE_COLORS = {
    HIGHWAY_COST: 'black', 
    MAIN_ROAD_COST: '#164018', 
    MINOR_ROAD_COST: '#26752a', 
    RURAL_ROAD_COST: 'orange', 
    SLOW_ROAD_COST: "#ffcccb",
    STREET_COST: "lightgrey"
    }

EDGE_SIZES = {HIGHWAY_COST: 5, 
              MAIN_ROAD_COST: 2, 
              MINOR_ROAD_COST: 1, 
              RURAL_ROAD_COST: 0.9, 
              SLOW_ROAD_COST: 0.8,
              STREET_COST: 0.7}


STANDARD_SIZE = 10
ROAD_CURVATURE = 3
SQUARE_DIAMETER = 10